spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  logging:
    level:
      root: INFO


